repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --fix
        language: python
        types_or: [python, pyi]
        additional_dependencies: [ruff]
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: python
        types_or: [python, pyi]
        additional_dependencies: [ruff]
      - id: mypy
        name: mypy
        entry: mypy --config-file pyproject.toml
        language: python
        pass_filenames: false
        additional_dependencies: [mypy]
